"""Initial schema: jobs and job_logs.

Written by hand rather than autogenerated. Autogenerate does not reliably emit
partial indexes, CHECK constraints or triggers, and a migration that silently
omitted ux_jobs_idempotency would remove the only thing enforcing duplicate
prevention. See specs/01-data-model.md section 7.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("5"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("progress", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('scheduled','pending','processing','completed','failed','cancelled')",
            name="ck_jobs_status",
        ),
        sa.CheckConstraint("job_type IN ('email','webhook','report','batch')", name="ck_jobs_type"),
        sa.CheckConstraint("priority BETWEEN 0 AND 9", name="ck_jobs_priority"),
        sa.CheckConstraint("max_attempts BETWEEN 1 AND 10", name="ck_jobs_max_attempts"),
        sa.CheckConstraint("attempts >= 0 AND attempts <= max_attempts", name="ck_jobs_attempts"),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="ck_jobs_progress"),
        sa.CheckConstraint(
            "idempotency_key IS NULL OR char_length(idempotency_key) <= 255",
            name="ck_jobs_idem_len",
        ),
        sa.CheckConstraint(
            "result IS NULL OR status = 'completed'", name="ck_jobs_result_when_completed"
        ),
        sa.CheckConstraint(
            "status <> 'scheduled' OR scheduled_at IS NOT NULL",
            name="ck_jobs_scheduled_has_time",
        ),
        sa.CheckConstraint(
            "status <> 'processing' OR (worker_id IS NOT NULL AND lease_until IS NOT NULL)",
            name="ck_jobs_processing_has_lease",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NOT NULL",
            name="ck_jobs_completed_after_started",
        ),
    )

    op.create_index(
        "ux_jobs_idempotency",
        "jobs",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        [sa.text("priority DESC"), "created_at"],
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_jobs_scheduled",
        "jobs",
        ["scheduled_at"],
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.create_index(
        "ix_jobs_lease",
        "jobs",
        ["lease_until"],
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.create_index("ix_jobs_status_created", "jobs", ["status", sa.text("created_at DESC")])
    op.create_index("ix_jobs_created", "jobs", [sa.text("created_at DESC")])

    op.create_table(
        "job_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.CheckConstraint("level IN ('info','warning','error')", name="ck_job_logs_level"),
    )
    op.create_index("ix_job_logs_job", "job_logs", ["job_id", "created_at"])

    # A trigger rather than SQLAlchemy's onupdate: the claim, completion and
    # reaper statements in later specs are issued as direct UPDATEs that never
    # pass through the ORM mapper, so an ORM-level hook would silently not fire
    # for exactly the writes whose timing matters most.
    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_jobs_updated_at
        BEFORE UPDATE ON jobs
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_jobs_updated_at ON jobs")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.drop_index("ix_job_logs_job", table_name="job_logs")
    op.drop_table("job_logs")
    for index in (
        "ix_jobs_created",
        "ix_jobs_status_created",
        "ix_jobs_lease",
        "ix_jobs_scheduled",
        "ix_jobs_claim",
        "ux_jobs_idempotency",
    ):
        op.drop_index(index, table_name="jobs")
    op.drop_table("jobs")
